version: "3.8"

services:

  elasticsearch:
    build:
      context: ./docker_compose/elasticsearch/
    image: gds-elasticsearch-m1
    expose:
      - "9200"
      - "9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - "./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties"
      - "./config/jvm.options:/usr/share/elasticsearch/config/jvm.options"
      - ./esdata:/usr/share/elasticsearch/data
  indexer:
    build:
      context: .
      dockerfile: ./docker_compose/data-service/Dockerfile
    depends_on:
      - elasticsearch
      - redis
      - worker
    environment:
      - GENOMIC_DATA_SERVICE_SETTINGS=/genomic_data_service/config/development.cfg
    command: make index_local
  worker:
    build:
      context: .
      dockerfile: ./docker_compose/data-service/Dockerfile
    depends_on:
      - elasticsearch
      - redis
    environment:
      - GENOMIC_DATA_SERVICE_SETTINGS=/genomic_data_service/config/development.cfg
    command: make worker
  redis:
    image: redis:alpine
    expose:
      - "6379"
