version: "3.9"
services:
  web:
    build: .
    image: gds
    depends_on:
      - elasticsearch
    ports:
      - 5000:5000
    volumes:
      - .:/opt/genomic-data-service/
    command:
      - make
      - up
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.port=9201
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9201:9201
      - 9300:9300
