version: 2.1

workflows:
  gds-tests:
    jobs:
      - lint
      - build-and-test:
          requires:
            - lint

jobs:
  lint:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/genomic_data_service
    steps:
      - checkout
      - run: pip install pre-commit==2.17.0
      - run: pre-commit run --all-files
  build-and-test:
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
    resource_class: medium
    working_directory: ~/genomic_data_service
    steps:
      - checkout
      - run:
          name: Build docker images
          command: docker-compose -f docker-compose-test-intel.yml build 
      - run:
          name: Tests
          command: |
            docker-compose -f docker-compose-test-intel.yml --env-file ./docker_compose/test.env up --exit-code-from genomic_data_service
      - run:
          name: Upload coverage
          command: |
              docker-compose -f docker-compose-test-intel.yml run --no-deps -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN genomic_data_service coveralls
