"""empty message

Revision ID: 1c19d9abe7d9
Revises: b81b25cdbeca
Create Date: 2021-02-16 11:48:12.531412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c19d9abe7d9'
down_revision = 'b81b25cdbeca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_expressions_dataset_accession'),
                    'expressions', ['dataset_accession'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expressions_dataset_accession'),
                  table_name='expressions')
    # ### end Alembic commands ###
