"""empty message

Revision ID: b81b25cdbeca
Revises: 80987cb30e48
Create Date: 2021-02-16 10:24:33.047907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b81b25cdbeca"
down_revision = "80987cb30e48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_expressions_feature_id"), "expressions", ["feature_id"], unique=False
    )
    op.create_index(
        op.f("ix_expressions_file_id"), "expressions", ["file_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expressions_file_id"), table_name="expressions")
    op.drop_index(op.f("ix_expressions_feature_id"), table_name="expressions")
    # ### end Alembic commands ###
